joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: [joint]

posvel_joint_trajectory_controller:
  type: posvel_controllers/JointTrajectoryController
  joints: [joint]

# joint_posvel_controller:
#  type: posvel_controllers/JointGroupPosVelController
#  joints: [j1,j2]
